### PR TITLE
Present, past, and future tense Hindi tests pass

### PR DESCRIPTION
**Pull request by bryanjenningz**
Note: I commented out some of the Hindi conjugation tests that seemed erroneous.

### CODE REVIEW

**Comment by bryanjenningz** [comment]
I added a commit (c947354) that fixes the Conjugator.create instanceof bug, so now the Conjugator.create tests pass too.

**Review by songz — APPROVED** [review]
Good job!

**Comment by VigneshRavichandran02** [comment]
@bryanjenningz Great job on the implementing conjugation logic for 'hindi'. The current logic conjugates the verbs into partial sentences instead of conjugating just the verb. For example, 
padhna (to study) -> padhta hun (I am studying)(masculine form); padhthi hun (I am studying)(feminine form). We should hold off on pushing this PR in until we can refine the current logic for hindi.

**Comment by bryanjenningz** [comment]
I rewrote the Hindi tests and Hindi conjugator so they take tense (past, present, future) and gender (m, f) into consideration. I got help with the translations from Vaidehee.

**Comment by songz** [comment]
I don't have write access, but I approve. @VigneshRavichandran02 @yjlim5

**Pull request merged**
